# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba05f560a5223721e64a946105754aaeddafafe786436280ed5e6b32eb1ab35e7ce5a81b7b626aeff4fdfa0f65919585a81375cc16c59f1f19d7ac524ff64fb6

test:
  secret_key_base: 5c0aa028e7d19552b4c2a6f26171e25792a0b698202e812a6debfc30d1bde713784426e3f64fa8510e3d8d6fbd5700f8f14649db8d24ff352b4be3ab7bd04150

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
